# Generated by Django 4.0.4 on 2023-04-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientearrendador',
            name='rut',
            field=models.CharField(blank=False, max_length=50, null=False, verbose_name='Rut'),
        ),
        migrations.AddField(
            model_name='dueñoestacionamiento',
            name='rut',
            field=models.CharField(blank=False, max_length=50, null=False, verbose_name='Rut'),
        ),
        migrations.AlterField(
            model_name='clientearrendador',
            name='idArrendador',
            field=models.AutoField(primary_key=False, serialize=False, verbose_name='Id de cliente'),
        ),
    ]
