# Generated by Django 4.0.4 on 2023-04-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clientearrendador_rut_dueñoestacionamiento_rut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='nombre',
            field=models.CharField(blank=False, max_length=50, null=False, verbose_name='Nombre comuna'),
        ),
    ]
