# Generated by Django 4.0.4 on 2023-04-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comuna_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='nombre',
            field=models.CharField(blank=False, max_length=50, null=False, verbose_name='Nombre banco'),
        ),
        migrations.AddField(
            model_name='region',
            name='nombre',
            field=models.CharField(blank=False, max_length=50, null=False, verbose_name='Nombre region'),
        ),
    ]
