# Generated by Django 4.0.4 on 2023-04-23 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_banco_nombre_region_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('idArriendo', models.AutoField(primary_key=False, serialize=False, verbose_name='Id Arriendo')),
                ('fechaInicio', models.CharField(max_length=50, verbose_name='Fecha incio')),
                ('fechaTermino', models.CharField(max_length=50, verbose_name='Fecha termino')),
                ('precioXhora', models.IntegerField(verbose_name='Precio por hora')),
            ],
        ),
        migrations.AlterField(
            model_name='clientearrendador',
            name='anio',
            field=models.IntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='clientearrendador',
            name='marca',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='clientearrendador',
            name='modelo',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='clientearrendador',
            name='patente',
            field=models.CharField(max_length=50, verbose_name='Patente'),
        ),
        migrations.AlterField(
            model_name='clientearrendador',
            name='tarjetaCredito',
            field=models.CharField(max_length=50, verbose_name='Tarjeta de credito'),
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('idEstacionamiento', models.AutoField(primary_key=False, serialize=False, verbose_name='Id de estacionamiento')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('comuna', models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE, to='core.comuna')),
                ('dueno', models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE, to='core.dueñoestacionamiento')),
            ],
        ),
    ]
