# Generated by Django 4.0.4 on 2023-04-23 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_arriendo_alter_clientearrendador_anio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientearrendador',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='clientearrendador',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='clientearrendador',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='clientearrendador',
            name='patente',
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.comuna'),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.dueñoestacionamiento'),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('idVehiculo', models.AutoField(primary_key=True, serialize=False, verbose_name='Id vehiculo')),
                ('patente', models.CharField(max_length=50, verbose_name='Patente')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('dueñoVehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.clientearrendador')),
            ],
        ),
    ]
