# Generated by Django 4.0.4 on 2023-04-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_clientearrendador_anio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientearrendador',
            name='nombre',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='dueñoestacionamiento',
            name='nombre',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre'),
        ),
    ]
