# Generated by Django 4.0.4 on 2023-04-23 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_clientearrendador_nombre_dueñoestacionamiento_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='dueñoVehiculo',
            new_name='duenoVehiculo',
        ),
        migrations.AlterField(
            model_name='clientearrendador',
            name='nombreUsuario',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre de usuario'),
        ),
        migrations.AlterField(
            model_name='clientearrendador',
            name='rut',
            field=models.CharField(max_length=50, unique=True, verbose_name='Rut'),
        ),
        migrations.CreateModel(
            name='DuenoEstacionamiento',
            fields=[
                ('idDueno', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de dueño')),
                ('nombreUsuario', models.CharField(max_length=50, unique=True, verbose_name='Nombre de usuario')),
                ('nombre', models.CharField(max_length=50, null=True, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=50, unique=True, verbose_name='Rut')),
                ('p_apellido', models.CharField(max_length=50, verbose_name='Primer apellido')),
                ('s_apellido', models.CharField(max_length=50, verbose_name='Segundo apellido')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('nombreCalle', models.CharField(max_length=50, verbose_name='Nombre calle')),
                ('cuentaBancaria', models.CharField(max_length=50, verbose_name='Cuenta bancaria')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comuna')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region')),
            ],
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.duenoestacionamiento'),
        ),
        migrations.DeleteModel(
            name='DueñoEstacionamiento',
        ),
    ]
