# Generated by Django 4.0.4 on 2023-04-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_dueñovehiculo_vehiculo_duenovehiculo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientearrendador',
            old_name='p_apellidos',
            new_name='p_apellido',
        ),
    ]
