# Generated by Django 4.0.4 on 2023-04-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_p_apellidos_clientearrendador_p_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='horario',
            field=models.CharField(max_length=20, null=True, verbose_name='Horario'),
        ),
    ]
