# Generated by Django 4.0.4 on 2023-04-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_estacionamiento_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='direccionEst',
            field=models.CharField(max_length=50, null=True, verbose_name='Direccion'),
        ),
    ]
