# Generated by Django 4.0.4 on 2023-06-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_servicio_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.CharField(max_length=400, verbose_name='descripcion'),
        ),
    ]
