# Generated by Django 4.0.4 on 2023-06-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_servicio_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Proveedor')),
                ('rut', models.CharField(max_length=50, verbose_name='Rut de  Proveedor')),
                ('nombreProveedor', models.CharField(max_length=50, verbose_name='Nombre de la Proveedor')),
                ('descripcion', models.CharField(max_length=400, verbose_name='descripcion')),
                ('direccion', models.CharField(max_length=400, verbose_name='direccion')),
                ('correo', models.CharField(max_length=400, verbose_name='correo')),
                ('especializacion', models.CharField(max_length=400, verbose_name='especializacion')),
                ('detalle', models.CharField(max_length=400, verbose_name='detalle')),
            ],
        ),
    ]
